.\" Man page for MancalaModel
.\" McKenzie Maurer - Spring 2017

.TH MancalaModel 1 "16 Nov 2017" "CSCI 241" "Oberlin College"

.SH NAME
.B MancalaModel
\- A model for playing mancala.

.SH SYNOPSIS
.B MancalaModel


.SH DESCRIPTION
Creates a MancalaModel struct which keeps track of the different parts of a mancala board,
including an array for each side of pits, the two player's banks, which player's turn it is,
and the state of the game, which is returned at the end of each attempted move.

